# Generated by Django 4.2.5 on 2023-09-22 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('senha', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=150)),
                ('email', models.TextField(max_length=150)),
                ('telefone', models.IntegerField()),
                ('id_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cadastro')),
            ],
        ),
    ]
