# Generated by Django 4.2.5 on 2023-09-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
