# Generated by Django 4.2.5 on 2023-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_agenda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='telefone',
            field=models.IntegerField(max_length=15),
        ),
    ]
