# Generated by Django 4.2.5 on 2023-09-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_agenda_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='telefone',
            field=models.TextField(max_length=150),
        ),
    ]
